### ISSUE TITLE
Spurious changing of upload destination in upload process

### ISSUE THREAD

**Issue by larsvilhuber** [ctjacobs/git-rdm#4]
I have configured Zenodo, but not Figshare. Uploading seems to proceed, and log shows creation of a fileset on Zenodo, but at the end, an attempt is made to check Figshare.

Context: see #3 .

Configuration of Zenodo: write, but not publish authorization.

Log file, see
[git-rdm-zenodo-figshare-log.txt](https://github.com/ctjacobs/git-rdm/files/915218/git-rdm-zenodo-figshare-log.txt)

Files do show correctly and completely on Zenodo.

**Comment by ctjacobs** [comment]
Zenodo is being used throughout but the warning message says "Figshare server" because of an outdated logging statement in PyRDM - I've generalised it now (see https://github.com/pyrdm/pyrdm/commit/34b9e89af0e059f805c3659fb4758ae34d6ffc4b). Verifying that files have been uploaded successfully to Zenodo hasn't been very well tested - I'd recommend just saying "Y"/"Yes" when asked if you want to continue, since you mentioned that the files do indeed show on Zenodo.
